services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: advisor_db
      POSTGRES_USER: advisor_user
      POSTGRES_PASSWORD: advisor_pass
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
